still fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,7 +33,6 @@ jobs:
       - name: Start Containers with Secrets
         env:
           # This maps your GitHub Secrets to shell variables
-          
           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
           MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
           MYSQL_USER: ${{ secrets.MYSQL_USER }}
@@ -48,6 +47,9 @@ jobs:
       
           # Create frontend config file for Vite
           echo "VITE_API_URL=$API_URL" > ./client/.env
+
+          ls -la .env || (echo ".env is missing!" && exit 1) # Stop if file is gone
+          cat .env | grep MYSQL # See if variables are inside (safely)
 
       - name: build images
         run: docker compose build
